import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google"; // Import Poppins
import "./globals.css";

// Load the Poppins font
const poppins = Poppins({
  variable: "--font-poppins",  // Define a variable for the font
  subsets: ["latin"],          // Choose the subset
  weight: ["400", "600", "700"],  // Optionally include different weights
});

// Existing font imports
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pet Boarding | Pets-zilla",
  description: "Generated by Salma",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased p-5`} // Add Poppins here
      >
        {children}
      </body>
    </html>
  );
}
